// A tiny catalog keeps example UI copy out of components and easy to translate.
export const copy = {
  title: "Airhop Transport",
  subtitle: "Two-device raw byte transfer",
  bleDemo: "BLE two-device flow",
  stepPermissions: "1. Grant nearby-device permission",
  stepRadio: "2. Start advertising and scanning",
  stepConnection: "3. Wait for a GATT connection",
  stepTransfer: "4. Select the BLE link and send bytes",
  pending: "Pending",
  complete: "Complete",
  active: "Active",
  startBle: "Start BLE",
  stopBle: "Stop BLE",
  bleStarting: "Starting BLE advertising and scanning...",
  bleRunning: "Advertising and scanning with the Airhop service UUID",
  bleStopped: "BLE stopped",
  bleUnavailable: "Bluetooth is powered off or unavailable",
  selected: "Selected",
  tapToSelect: "Tap a link to select it",
  role: "Role",
  rssi: "RSSI",
  bytes: "bytes",
  accelerators: "Optional accelerators",
  startAccelerators: "Start Wi-Fi / LAN",
  acceleratorsStarted: "Wi-Fi and LAN startup requested",
  stopped: "Stopped",
  starting: "Starting transports...",
  running: "Listening for nearby devices",
  stopping: "Stopping transports...",
  error: "Transport error",
  start: "Start",
  stop: "Stop",
  messageLabel: "Message",
  messagePlaceholder: "Type data to send",
  send: "Send",
  noLink: "No connected link yet",
  links: "Links",
  noLinks: "No devices connected",
  events: "Recent events",
  noEvents: "No events yet",
  connected: "Connected",
  disconnected: "Disconnected",
  received: "Received",
  sent: "Sent",
  lanFound: "LAN peer found",
  permissionDenied: "Nearby-device permission was denied",
  wifiAwarePairing: "Wi-Fi Aware pairing",
  pairedDevices: "Paired devices",
  pairingUnsupported: "Wi-Fi Aware pairing is unavailable on this device",
  findDevice: "Find device",
  becomeDiscoverable: "Become discoverable",
  pairingActionFind: "Choose a nearby Airhop device",
  pairingActionDiscoverable: "Allow another Airhop device to pair",
  pairingCancel: "Cancel",
  pairingUnavailable: "Wi-Fi Aware is unavailable",
} as const;
