// A tiny catalog keeps example UI copy out of components and easy to translate.
export const copy = {
  title: "Airhop Transport",
  subtitle: "Two-device raw byte transfer",
  stopped: "Stopped",
  starting: "Starting transports...",
  running: "Listening for nearby devices",
  stopping: "Stopping transports...",
  error: "Transport error",
  start: "Start",
  stop: "Stop",
  messageLabel: "Message",
  messagePlaceholder: "Type data to send",
  send: "Send",
  noLink: "No connected link yet",
  links: "Links",
  noLinks: "No devices connected",
  events: "Recent events",
  noEvents: "No events yet",
  connected: "Connected",
  disconnected: "Disconnected",
  received: "Received",
  sent: "Sent",
  lanFound: "LAN peer found",
  permissionDenied: "Nearby-device permission was denied",
  wifiAwarePairing: "Wi-Fi Aware pairing",
  pairedDevices: "Paired devices",
  pairingUnsupported: "Wi-Fi Aware pairing is unavailable on this device",
  findDevice: "Find device",
  becomeDiscoverable: "Become discoverable",
  pairingActionFind: "Choose a nearby Airhop device",
  pairingActionDiscoverable: "Allow another Airhop device to pair",
  pairingCancel: "Cancel",
  pairingUnavailable: "Wi-Fi Aware is unavailable",
} as const;
